name: socialv
description: A mobile programmingg  project.
publish_to: 'none'

version: 7.3.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Common packages
  nb_utils: ^6.1.3
  google_fonts: 6.1.0
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  lottie: ^3.1.0

  # Media
  image_picker: ^1.0.7
  file_picker: ^6.2.0
  just_audio: ^0.9.36
  syncfusion_flutter_pdfviewer: ^24.2.8
  photo_view: ^0.14.0
  appinio_video_player: ^1.3.0
  giphy_get: ^3.5.4
  video_player: ^2.8.3
  youtube_player_flutter: ^9.0.0
  visibility_detector: ^0.4.0+2
  flutter_svg: ^2.0.10+1

  # APIs
  http: ^1.2.1
  intl: ^0.18.1
  html: ^0.15.4

  flutter_html: ^3.0.0-beta.1
  flutter_html_table: ^3.0.0-beta.2
  

  # State Management Technique
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2

  # Share
  share_plus: ^7.2.2
  flutter_custom_tabs: ^2.0.0+1



  # Story
  story_time: ^1.0.6
  numberpicker: ^2.1.2

  # Others
  flutter_emoji: ^2.5.1
  flutter_mentions: ^2.0.1
  flutter_portal: ^0.4.0
  linear_timer: ^2.0.0
  country_picker: ^2.0.25
  any_link_preview: ^3.0.1
  string_contains: ^2.4.0
  carousel_slider: ^4.2.1
: ^1.3.6

  # Agora
  agora_rtc_engine: ^5.2.0
  permission_handler: ^11.3.0

  flutter_localizations:
    sdk: flutter
  # go_router: ^12.1.1
dependency_overrides:
  video_player: ^2.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1

  output



flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/flag/
    - assets/icons/
    - assets/lottie/

